<?php
namespace API\Controllers;

use API\Library;
use API\Model;

class Index extends Library\BaseController
{

	public function __construct()
	{
		parent::__construct();
	}

	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
	}

}