<?php
namespace API\Controllers;

use API\Library;
use API\Model;

class Monster extends Library\BaseController
{
	private $_db;

	public function __construct()
	{
		parent::__construct();

		$this->_db = new Model\MonsterModel();
	}

	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
    }
    
    public function getMonster()
    {
        /*if($this->_auth->validate_token($this->_headers['token'], $this->_headers['user'])['level'] != 4)
        {
            return $this->_output->output(401, "Authorization Failed", false);
        }*/

        $mon = $this->_db->get_monster(['min' => 1, 'max' => 1]);
            
        return $this->_output->output(200, $mon, false);
    }

    public function updateStats()
    {
        if($this->_auth->validate_token($this->_headers['token'], $this->_headers['user'])['level'] != 4)
        {
            return $this->_output->output(401, "Authorization Failed", false);
        }
        
        $this->_db->update_stats($this->_params[0], $this->_params[1]);

        return $this->_output->output(200, "Stats Updated", false);
    }
}