<?php
namespace API\Controllers;

use API\Library;
use API\Model;

class Shop extends Library\BaseController
{
	private $_db;

	public function __construct()
	{
		parent::__construct();

		$this->_db = new Model\ShopModel();
	}

	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
	}
	
	public function list_shops()
	{
		//list all shops that are "open"
	}

	public function shop_info()
	{
		//displays stored info on the shop, lore, level restrictions, specialty etc
	}

	public function get_inventory()
	{
		//get all inventory of shop, requires shop id and user id
	}

	public function buy()
	{
		//needs shop id, user id, item id
	}

	public function sell()
	{
		//same as above, also needs to check if the item is equipped
	}

	public function services()
	{
		//future
	}
    
}