<?php
namespace API\Controllers;

use API\Library;
use API\Model;

class Stats extends Library\BaseController
{
	private $_db;

	public function __construct()
	{
		parent::__construct();

		$this->_db = new Model\StatsModel();
	}

	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function currency()
    {
        $limit = $this->_params[0];

        $outcome = json_encode($this->_db->gold_stats($limit));

        return $this->_output->output(200, $outcome, true);
	}
	
	public function pve_win()
	{

	}

	public function pve_loss()
	{

	}

	public function level()
	{
		
	}
}