<?php
namespace API\Controllers;

use API\Library;
use API\Model;

class Viewer extends Library\BaseController
{
    private $_db;
    private $_twitch;

	public function __construct()
	{
		parent::__construct();

        $this->_db = new Model\ViewerModel();
        $this->_twitch = new Library\Twitch();
	}

	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
    }
    
    public function addUser()
    {
        $username = $this->_params[0];
        $id       = $this->_twitch->get_user_id($username);

        $output = $this->_db->add_user($id, $username);

        return $this->_output->output(200, $output, false);
    }

    public function updateUser()
    {
        $id = $this->_twitch->get_user_id($this->_params[0]);
        $mode = $this->_params[1];

        $output = $this->_db->update_user($id, $mode);

        return $this->_output->output(200, $output, false);
    }
}